name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main          
      
      - name: Use the version
        run: |
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          echo "New release version ${{ steps.version.outputs.version }}"

  backend-build-and-test:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
        cache-dependency-path: ./src/**/packages.lock.json
    - name: Restore packages
      run: dotnet restore ./src/Todo.Api.sln --locked-mode
    - name: Build
      run: dotnet build ./src/Todo.Api.sln --no-restore --configuration Release
    - name: Test      
      run: dotnet test ./src/Todo.Api.sln --no-restore --no-build --configuration Release --logger trx --results-directory "TestResults"
      if: github.ref != 'refs/heads/main'
    - name: Upload dotnet test results      
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-test-results
        path: TestResults        
      if: github.ref != 'refs/heads/main'
    - name: Publish
      run: dotnet publish ./src/api/Todo.Api.csproj --no-restore --no-build --configuration Release --output ./publish
      if: github.ref == 'refs/heads/main'
    - name: Upload dotnet artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api
        path: ./publish
      if: github.ref == 'refs/heads/main'

  frontend-build-and-test:
    needs: versioning
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/web

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: npm
        cache-dependency-path: ./src/web
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: web
        path: ./src/web/dist
      if: github.ref == 'refs/heads/main'
      
  backend-lint:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: "main"
          VALIDATE_ALL_CODEBASE: "false"
          VALIDATE_YAML: "true"
          VALIDATE_CSHARP: "true"
          VALIDATE_JAVASCRIPT_ES: "true"
          VALIDATE_TYPESCRIPT_ES: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.ref != 'refs/heads/main'

  dependency-review:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4        
        with:
          comment-summary-in-pr: always
          base-ref: main
          head-ref: main
    if: github.ref != 'refs/heads/main'

  code-security-check:
    needs: versioning
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: csharp
          build-mode: none
        - language: javascript-typescript
          build-mode: none
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
    if: github.ref != 'refs/heads/main'    

  build-docker-image:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: app
        merge-multiple: false

    