name: deploy
run-name: Deploy ${{ github.repository }} to ${{ inputs.environment}} by ${{ github.actor }}

on:  
  workflow_call:
    inputs:
      version: 
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy-to-azure:
    name: Azure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    env:
      WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
      PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    steps:
    - name: Validate environment input
      run: |
        if [[ "${{ inputs.environment }}" != "Production" && "${{ inputs.environment }}" != "Staging" ]]; then
          echo "Invalid environment: ${{ inputs.environment }}. Allowed values are 'Production' or 'Staging'."
          exit 1
        fi
    - name: Deploy Docker to Azure
      id: deploy-docker-to-azure
      uses: azure/webapps-deploy@v3
      with:        
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ env.PUBLISH_PROFILE }}
        images: 'ghcr.io/${{ github.repository }}:${{ inputs.version }}'