name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        name: api
        workflow: Build
        run_id: ${{ github.event.workflow_run.id }}
